### ISSUE TITLE
Roda e Pneu para motores 10:1

### ISSUE THREAD

**Issue by raphera** [Tamandutech/LineFollower_Braia_Mechanics#1]
Pneus de 32mm, que usamos nos motores 30:1, não são bons com motores 10:1 devido ao torque menor que o motor oferece.

Necessário desenvolver um conjunto de roda e pneus otimizados para motores 10:1 levando em consideração a distância percorrida por giro da roda em cada um dos tamanhos.

<h3>Pneu que usamos atualmente:</h3>

![Image](https://user-images.githubusercontent.com/50784405/173164104-99a6624f-ea4f-40b1-834b-5464896a558c.png)

O comprimento da roda de 32mm é 100mm (o carrinho percorre 10cm a cada volta da roda), para o motor 10:1 seria equivalente a uma roda de 33mm ou 10mm de diâmetro. 

**⚠️ Recomendo o diâmetro da roda ser de 24mm (~75,4mm de comprimento) devido a altura do robô.**

**⚠️ Sempre validar as medidas utilizando o robô modelado no fusion, que está com as medidas reais.**

**Comment by BiaStorch** [comment]
![image](https://user-images.githubusercontent.com/106498615/174506059-805a98a6-0075-49e4-aa1e-6a485f7f126a.png)
ainda estou no solid pq o fusion está travando

**Comment by BiaStorch** [comment]
![image](https://user-images.githubusercontent.com/106498615/174506102-d6d0b63e-bd25-4410-9c1c-ad484f4384db.png)
ta exatamente do tamanho do eixo entao se imprimir assim acho q nem entra pq tem uma tolerância da espessura do filamento que não considerei

**Comment by Matheus-de-Sousa** [comment]
Também é importante, desenvolver o pneu de forma que ele possua boa aderência ao chão, para o robô não deslizar facilmente e após a finalização da roda, precisaremos ajustar os parâmetros do robô para que o sistema de controle seja adequado às novas rodas.

**Comment by raphera** [comment]
Em andamento
