### ISSUE TITLE
Suporte Frontal

### ISSUE THREAD

**Issue by raphera** [Tamandutech/LineFollower_Braia_Mechanics#2]
Necessário criar um apoio frontal para o robô, substituindo a roda boba.

⚠️ Atentar a altura do robô com as novas rodas (#1 )

**Comment by BiaStorch** [comment]
![image](https://user-images.githubusercontent.com/106498615/174507744-62b69e65-e5bf-4951-a8fa-3cc63dc2fde9.png)
eu estou com umas esferas de rolamento de 3mm pensei em fazer um (funil com abertura de 2.5 na ponta (acho q ai fica 0.67 da esfera para fora) usar um pino para atravessar o funil de forçar a esfera para ficar em contato com o chao e usar 2 parafusos m2 para parafusar esse pino na PCB

**Comment by BiaStorch** [comment]
![WhatsApp Image 2022-06-19 at 22 00 10 (1)](https://user-images.githubusercontent.com/106498615/174508037-0ef7c817-d289-4eec-ac06-75f5ff480df9.jpeg)
esfera

**Comment by BiaStorch** [comment]
pensei em usar esfera de 5mm mas quanto maior a esfera maior o suporte e mais espaço par fixação além do mais só precisamos de 1 ponto de apoio. tenho esfera de 0.62" (1,5748mm) e também são classe 3

**Comment by Matheus-de-Sousa** [comment]
Legal Bia, porém acho que é bom evitar usar parafusos na pcb, pois passamos muitas trilhas nela e componentes, deixando tudo bem concentrado para ficar pequena, então ficaria difícil colocar um parafuso, mas dá para fazer um encaixe pra conectar o suporte na pcb, através dele e imprimir esse encaixe.

**Comment by raphera** [comment]
Suporte frontal concluído, segue imagens:

![image](https://user-images.githubusercontent.com/50784405/179360490-3fe5f5f5-762f-49c0-9db7-4e2bc91f1c5a.png)

![image](https://user-images.githubusercontent.com/50784405/179360505-224bc204-c656-459a-afd2-88ccb892af4c.png)

![image](https://user-images.githubusercontent.com/50784405/179360515-73934e2b-d076-4a44-8e4f-ea61bd2e13af.png)

![image](https://user-images.githubusercontent.com/50784405/179360526-f62cfd56-89ac-4103-9fa3-75103b2cc513.png)

![image](https://user-images.githubusercontent.com/50784405/179360533-79777604-9be9-4263-b492-40753cb63444.png)

![image](https://user-images.githubusercontent.com/50784405/179360541-492de0cd-3158-4cd1-8c85-abfe2399e76b.png)
